### ISSUE TITLE
WI - Bug Fakenodo

### ISSUE THREAD

**Issue by karyouben** [Mantecado-hub/mantecado-hub-2#61]
-  **Qué sucede.**

Se muestra error al intentar subir datasets nuevos al proyecto en los test.

- **Qué se esperaba que sucediera.**

Que se permita subir datasets nuevos al proyecto en los test.

- **Capturas de pantalla o logs, si es posible.**
![Image](https://github.com/user-attachments/assets/71488475-8998-4505-9e9a-b0f5defec512)

**Comment by Pavlo-Rods** [comment]
Hay que adaptar los test que ya estan hechos a la nueva versión de Fakenodo ya que actualmente no funcionan, puesto que utilizan los métodos antiguos.
No deben ser muy dificiles de adaptar
